services:
  - type: web
    name: analytiq-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AWS_DEFAULT_REGION
        value: ap-southeast-2
